CREATE TABLE `db_smart`.`pedidos` (
  `ord_id` INT NOT NULL,
  `ord_carteira` VARCHAR(45) NULL,
  `ord_aceitar_boleto` CHAR(1) NULL,
  `ord_aceitar_cartao` CHAR(1) NULL,
  `ord_aceitar_cartao_parcelas` CHAR(1) NULL,
  `ord_status` CHAR(1) NULL,
  `ord_emails` BLOB NULL,
  `ord_pagamento_minimo` VARCHAR(45) NULL,
  `ord_criado_em` DATE NULL,
  `ord_atualizar` CHAR(1) NULL,
  `ord_vencimento` DATE NULL,
  `ord_receber_ate` DATE NULL,
  `ord_multa_atraso` DECIMAL NULL,
  `ord_juros_dia` DECIMAL NULL,
  `ord_entrega` VARCHAR(45) NULL,
  `ord_nome` VARCHAR(500) NULL,
  `ord_email` VARCHAR(200) NULL,
  `ord_celular` VARCHAR(45) NULL,
  PRIMARY KEY (`ord_id`));

 
CREATE TABLE `db_smart`.`pedidos_itens` (
  `oit_id` INT NOT NULL,
  `oit_pedido` DECIMAL NULL,
  `oit_titulo` VARCHAR(500) NULL,
  `oit_tipo` DECIMAL NULL,
  `oit_tipo_id` DECIMAL NULL,
  `oit_quantidade` DECIMAL NULL,
  `oit_valor` DECIMAL NULL,
  PRIMARY KEY (`oit_id`));
  
  
  
CREATE TABLE `db_smart`.`dividas_pagamentps` (
  `pgm_id` INT NOT NULL,
  `pgm_local` VARCHAR(45) NULL,
  `pgm_carteira` VARCHAR(45) NULL,
  `pgm_pedido` VARCHAR(45) NULL,
  `pgm_valor` VARCHAR(45) NULL,
  `pgm_parcelas` VARCHAR(45) NULL,
  `pgm_parcelas_pagas` VARCHAR(45) NULL,
  `pgm_status` VARCHAR(45) NULL,
  `pgm_pagador_nome` VARCHAR(45) NULL,
  `pgm_pagador_email` VARCHAR(45) NULL,
  `pgm_pagador_celular` VARCHAR(45) NULL,
  `pgm_pagador_cpf` VARCHAR(45) NULL,
  `pgm_pagador_genero` VARCHAR(45) NULL,
  `pgm_pagador_nascimento` VARCHAR(45) NULL,
  `pgm_pagador_razao` VARCHAR(45) NULL,
  `pgm_pagador_cnpj` VARCHAR(45) NULL,
  `pgm_metodo` VARCHAR(45) NULL,
  `pgm_intermediario` VARCHAR(45) NULL,
  `pgm_intermediario_code` VARCHAR(45) NULL,
  `pgm_intermediario_status` VARCHAR(45) NULL,
  `pgm_intermediario_taxa` VARCHAR(45) NULL,
  `pgm_intermediario_fixo` VARCHAR(45) NULL,
  `pgm_intermediario_variavel` VARCHAR(45) NULL,
  `pgm_intermediario_total` VARCHAR(45) NULL,
  `pgm_intermediario_disponivel` VARCHAR(45) NULL,
  `pgm_boleto_url` VARCHAR(45) NULL,
  `pgm_boleto_digitavel` VARCHAR(45) NULL,
  `pgm_cartao_metodo` VARCHAR(45) NULL,
  `pgm_cartao_bandeira` VARCHAR(45) NULL,
  `pgm_cartao_numero` VARCHAR(45) NULL,
  `pgm_cartao_mes` VARCHAR(45) NULL,
  `pgm_cartao_ano` VARCHAR(45) NULL,
  `pgm_cartao_nome` VARCHAR(45) NULL,
  `pgm_cartao_codigo` VARCHAR(45) NULL,
  `pgm_cartao_recobrancas` VARCHAR(45) NULL,
  `pgm_endereco_cep` VARCHAR(45) NULL,
  `pgm_endereco_cidade` VARCHAR(45) NULL,
  `pgm_endereco_logradouro` VARCHAR(45) NULL,
  `pgm_endereco_numero` VARCHAR(45) NULL,
  `pgm_endereco_bairro` VARCHAR(45) NULL,
  `pgm_endereco_complemento` VARCHAR(45) NULL,
  `pgm_comissao_custo` VARCHAR(45) NULL,
  `pgm_comissao_taxa` VARCHAR(45) NULL,
  `pgm_comissao_fixo` VARCHAR(45) NULL,
  `pgm_comissao_variavel` VARCHAR(45) NULL,
  `pgm_comissao_total` VARCHAR(45) NULL,
  `pgm_comissao_paga` VARCHAR(45) NULL,
  `pgm_criado_em` VARCHAR(45) NULL,
  `pgm_pago_em` VARCHAR(45) NULL,
  `pgm_cliente_taxa` VARCHAR(45) NULL,
  `pgm_cliente_liquido` VARCHAR(45) NULL,
  `pgm_disponivel_futuro` VARCHAR(45) NULL,
  `pgm_disponivel_liberado` VARCHAR(45) NULL,
  `pgm_disponivel_intermediario` VARCHAR(45) NULL,
  `pgm_disponivel_empresa` VARCHAR(45) NULL,
  `pgm_disponivel_cliente` VARCHAR(45) NULL,
  PRIMARY KEY (`pgm_id`));
  
  
  CREATE TABLE `db_smart`.`recebimentos` (
  `prc_id` INT NOT NULL,
  `prc_local` VARCHAR(45) NULL,
  `prc_carteira` VARCHAR(45) NULL,
  `prc_pagamento` VARCHAR(45) NULL,
  `prc_valor` VARCHAR(45) NULL,
  `prc_numero` VARCHAR(45) NULL,
  `prc_disponivel_em` VARCHAR(45) NULL,
  `prc_disponibilizada` VARCHAR(45) NULL,
  `prc_status` VARCHAR(45) NULL,
  `prc_intermediario_taxa` VARCHAR(45) NULL,
  `prc_empresa` VARCHAR(45) NULL,
  `prc_cliente` VARCHAR(45) NULL,
  PRIMARY KEY (`prc_id`));

  
  CREATE TABLE `db_smart`.`carteiras` (
  `wal_id` INT NOT NULL,
  `wal_title` VARCHAR(45) NULL,
  `wal_key` VARCHAR(45) NULL,
  `wal_secret` VARCHAR(45) NULL,
  `wal_pin` VARCHAR(45) NULL,
  `wal_saque_automatico` VARCHAR(45) NULL,
  `wal_multas` VARCHAR(45) NULL,
  `wal_antecipacao` VARCHAR(45) NULL,
  `wal_antecipacao_tipo` VARCHAR(45) NULL,
  `wal_antecipacao_dias` VARCHAR(45) NULL,
  `wal_soft_descriptor` VARCHAR(45) NULL,
  `wal_pacelamento_max` VARCHAR(45) NULL,
  `wal_aceitar_boleto` VARCHAR(45) NULL,
  `wal_aceitar_cartao` VARCHAR(45) NULL,
  `wal_cartao_comissao_taxa` VARCHAR(45) NULL,
  `wal_cartao_comissao_fixo` VARCHAR(45) NULL,
  `wal_taxa_cartao_antecipacao` VARCHAR(45) NULL,
  `wal_banco` VARCHAR(45) NULL,
  `wal_agencia` VARCHAR(45) NULL,
  `wal_conta` VARCHAR(45) NULL,
  `wal_intermediary` VARCHAR(45) NULL,
  `wal_intermediary_settings` VARCHAR(45) NULL,
  PRIMARY KEY (`wal_id`));

  
  CREATE TABLE `db_smart`.`saques` (
  `saq_id` INT NOT NULL,
  `saq_carteira` VARCHAR(45) NULL,
  `saq_criado_em` VARCHAR(45) NULL,
  `saq_valor` VARCHAR(45) NULL,
  `saq_status` VARCHAR(45) NULL,
  `saq_intermediario` VARCHAR(45) NULL,
  `saq_intermediario_code` VARCHAR(45) NULL,
  `saq_pago_em` VARCHAR(45) NULL,
  PRIMARY KEY (`saq_id`));

  
  